### ISSUE TITLE
Add a cancel tag on touchpad while tool is drawing

### ISSUE THREAD

**Issue by fijal** [lightscapevr/vr-sketch-4#25]
I can do it myself, but need some help :-)

Generally - once we start drawing it's not THAT obvious how to cancel. Touchpad is not doing anything, so we can add the "cancel" tag and be happy

**Comment by arigo** [comment]
Grep for SetControllerHints() in ToolBase.cs

**Comment by fijal** [comment]
No, not as a help on the side, noone seems to read those - a straight sign "Cancel" on the touchpad itself. I got the canvas running at the end, but it's a whole lot of changing completely insane defaults. BaroqueUI maybe should have some canvas prefabs to do those sort of things.

**Comment by fijal** [comment]
Just like scroll wheel and sign "X copies"

**Comment by arigo** [comment]
Right.  Well, that means the controller hints are pointless, too, and should be killed and replaced with something else...  And yes, right now, to do it like you say, you need to make a model with roughly the same shape as the touchpad, give it a texture that is a rendertexture from a dialog with BaroqueUI's "Dialog" component, and position it carefully so that it is over the original touchpad...  I agree it could be done more automatically if we figure out good defaults for all of this.

**Comment by fijal** [comment]
I mean people read them "a bit", when they're completely confused. I haven't had a single person find the grip button just by reading hints that there is a button for example. I think that should be replaced with a in-VR tutorial and a button in sketchup saying "run tutorial"  that would show you a big controller with all the explanations. That's quite a major undertaking though. But besides the "completely confused" phase people don't read the hints. They do read the "X copies" though, somehow.

**Comment by arigo** [comment]
a806ee9 changes the touchpad color to dark red.  I think it's giving good feedback, both that you can click that touchpad to do a red action (i.e. cancel), and that we're in a different mode than before.

**Comment by fijal** [comment]
I think that's good enough

**Comment by arigo** [comment]
Adding the word "cancel" on it is just a matter of making the right texture...
