### ISSUE TITLE
Teleport through glass

### ISSUE THREAD

**Issue by fijal** [lightscapevr/vr-sketch-4#34]
One of the main problems I encounter when people try is teleporting through glass. It's counter intuitive and hard to explain. Also *everyone* has glass in their model. Probably it's enough to say something like "walls of transparency more than X don't stop the teleport"

**Comment by arigo** [comment]
It makes no sense that we should be able to *move* through glass.  But "intuitively", yes, we should be able to teleport through glass.  Who knew intuition would work like that for alien concepts like teleporting.  I guess it's because we associate it more with "I can see through glass so I should be able to teleport".

**Comment by fijal** [comment]
No idea :-) Maybe because glass does not look like glass?

**Comment by arigo** [comment]
I think it's really because "I can see there, so I should be able to teleport there".  Done.
